### PR TITLE
fix: update all deps and tests

### PR DESCRIPTION
**Pull request by knownasilya**
BREAKING CHANGES: dropped node v6 and ember < 3.8

Note: we switched from ember-mocha to ember-qunit because ember-mocha is not maintained.

### CODE REVIEW

**Comment by knownasilya** [comment]
looks like the travis config might need updating to use yarn. That's my guess.

**Comment by knownasilya** [comment]
Looks like an issue with mocha.

**Comment by cowboyd** [comment]
:/

**Comment by knownasilya** [comment]
Might be worthwhile to move back to qunit, since ember-mocha is 4 major versions behind.
https://github.com/emberjs/ember-mocha/pull/334

**Comment by taras** [comment]
@knownasilya Can I help with this?

**Comment by knownasilya** [comment]
I think we need to convert to qunit, if you have time feel free to submit agains this PR.

**Comment by taras** [comment]
@knownasilya `ERROR: Uncaught Error: Compile Error: state is not a helper at` any idea what this might be about?

**Comment by taras** [comment]
I have bandwidth to fix it now. What is going on with this?

**Pull request merged**
